# Generated by Django 3.2.23 on 2024-01-03 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20240101_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishItem',
        ),
    ]
